service: autotrainer-enrolment-api

# Use serverless-webpack plugin to transpile ES6/ES7
plugins:
  - serverless-webpack
  - serverless-domain-manager

# Enable auto-packing of external modules
custom:
  webpackIncludeModules: true
  customDomain:
    domainName: api.learn.actuarialpartners.com
    certificateName: '*.actuarialpartners.com'
    endpointType: 'regional'
    basePath: enrolment # This will be prefixed to all routes
    stage: ${self:provider.stage}
    createRoute53Record: true


provider:
  name: aws
  runtime: nodejs6.10
  stage: prod
  region: ap-southeast-1

  # 'iamRoleStatement' defines the permission policy for the Lambda function.
  # In this case Lambda functions are granted with permissions to access DynamoDB.
  # added access to cognito-idp to get user info
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
        - dynamodb:BatchGetItem
        - dynamodb:BatchWriteItem
      Resource: "arn:aws:dynamodb:ap-southeast-1:*:*"
    - Effect: Allow
      Action:
        - cognito-idp:AdminGetUser
      Resource: "arn:aws:cognito-idp:ap-southeast-1:*:*"

functions:
  # Defines an HTTP API endpoint that calls the main function in create.js
  # - path: url path is /notes
  # - method: POST request
  # - cors: enabled CORS (Cross-Origin Resource Sharing) for browser cross
  #     domain api call
  # - authorizer: authenticate using the AWS IAM role
  create:
    handler: create.main
    events:
      - http:
          path: /
          method: post
          cors: true
          authorizer: aws_iam
  get:
    # Defines an HTTP API endpoint that calls the main function in get.js
    # - path: url path is /notes/{id}
    # - method: GET request
    handler: get.main
    events:
      - http:
          path: /{id}
          method: get
          cors: true
          authorizer: aws_iam
  list:
    # Defines an HTTP API endpoint that calls the main function in list.js
    # - path: url path is /notes
    # - method: GET request
    handler: list.main
    events:
      - http:
          path: /
          method: get
          cors: true
          authorizer: aws_iam
  list_invited:
    # Defines an HTTP API endpoint that calls the main function in list.js
    # - path: url path is /notes
    # - method: GET request
    handler: list_invited.main
    events:
      - http:
          path: /invited
          method: get
          cors: true
          authorizer: aws_iam
  students:
    # Defines an HTTP API endpoint that calls the main function in get.js
    # - path: url path is /notes/{id}
    # - method: GET request
    handler: students.main
    events:
      - http:
          path: /{id}/students
          method: get
          cors: true
          authorizer: aws_iam
  attend:
    # Defines an HTTP API endpoint that calls the main function in get.js
    # - path: url path is /notes/{id}
    # - method: GET request
    handler: attend.main
    environment:
      SENDGRID_API_KEY: ${ file(./keys.json):sendgrid }
    events:
      - http:
          path: /{id}/attend/{moduleId}
          method: post
          cors: true
          authorizer: aws_iam
  invite:
    # Defines an HTTP API endpoint that calls the main function in ATTEND.js
    # - path: url path is /enrolment/{id}/invite
    # - method: post request
    handler: invite.main
    environment:
      SENDGRID_API_KEY: ${ file(./keys.json):sendgrid }
    events:
      - http:
          path: /{id}/invite
          method: post
          cors: true
          authorizer: aws_iam
  mark_progress:
    # Defines an HTTP API endpoint that calls the main function in ATTEND.js
    # - path: url path is /enrolment/{id}/invite
    # - method: post request
    handler: mark_progress.main
    events:
      - http:
          path: /{id}/mark_progress/{moduleId}
          method: post
          cors: true
          authorizer: aws_iam
  cert_lookup:
    # Defines an HTTP API endpoint that calls the main function in ATTEND.js
    # - path: url path is /enrolment/{id}/invite
    # - method: post request
    handler: cert_lookup.main
    events:
      - http:
          path: /cert_lookup
          method: post
          cors: true
          authorizer: aws_iam
