service: autotrainer-ident-api

# Use serverless-webpack plugin to transpile ES6/ES7
plugins:
  - serverless-webpack
  - serverless-domain-manager

# Enable auto-packing of external modules
custom:
  webpackIncludeModules: true
  customDomain:
    domainName: apilearn.actuarialpartners.com
    endpointType: 'regional'
    basePath: ident # This will be prefixed to all routes
    stage: ${self:provider.stage}
    createRoute53Record: true

provider:
  name: aws
  runtime: nodejs6.10
  stage: prod
  region: ap-southeast-1

  # 'iamRoleStatement' defines the permission policy for the Lambda function.
  # In this case Lambda functions are granted with permissions to access DynamoDB.
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:ap-southeast-1:*:*"
    - Effect: Allow
      Action:
        - cognito-idp:AdminGetUser
      Resource: "arn:aws:cognito-idp:ap-southeast-1:*:*"


functions:
  # Defines an HTTP API endpoint that calls the main function in create.js
  # - path: url path is /notes
  # - method: POST request
  # - cors: enabled CORS (Cross-Origin Resource Sharing) for browser cross
  #     domain api call
  # - authorizer: authenticate using the AWS IAM role
  check:
    handler: check.main
    events:
      - http:
          path: /check
          method: post
          cors: true
          authorizer: aws_iam
  test:
    handler: test.main
    events:
      - http:
          path: /test
          method: post
          cors: true
          authorizer: aws_iam
  userInfo:
    handler: userInfo.main
    events:
      - http:
          path: /user_info
          method: post
          cors: true
          authorizer: aws_iam
